module.exports = ["Abu Dhabi", "Ajman", "Al Ain", "Dubai", "Ras Al-Khaimah", "Salta", "Avellaneda", "Bahia Blanca", "Balcarce",
"Brandsen", "Campana", "Chacabuco", "Colon", "Del Viso", "Isidro Casanova", "Junin", "La Plata", "Lomas de Zamora", "Luis Guillon",
"Lujan", "Mar del Plata", "Moron", "Olavarria", "Pergamino", "Pinamar", "Quilmes", "San Antonio de Padua", "San Fernando",
"San Isidro", "San Nicolas de los Arroyos", "San Pedro", "Tandil", "Tortuguitas", "Trenque Lauquen", "Vicente Lopez", "Villa Gesell",
"Zarate", "Buenos Aires", "Concepcion del Uruguay", "Gualeguaychu", "Parana", "La Rioja", "Santiago del Estero", "Resistencia",
"San Juan", "General Pico", "Santa Rosa", "Mendoza", "San Martin", "San Rafael", "Posadas", "Formosa", "Neuquen",
"San Martin de los Andes", "San Carlos de Bariloche", "Viedma", "Rafaela", "Rosario", "Santa Fe", "Venado Tuerto",
"Villa Constitucion", "San Miguel de Tucuman", "Comodoro Rivadavia", "Puerto Madryn", "Rio Grande", "Ushuaia", "Corrientes",
"Cordoba", "Rio Cuarto", "San Francisco", "Villa Maria", "Jujuy", "Caleta Olivia", "Rio Gallegos", "Canberra", "Barwon Downs",
"Albury", "Armidale", "Ballina", "Batemans Bay", "Bathurst", "Broken Hill", "Cessnock", "Coffs Harbour", "Dubbo", "Goulburn",
"Grafton", "Griffith", "Kiama", "Victoria Point", "Katoomba", "Lismore", "Lithgow", "Maitland", "Craigieburn", "Muswellbrook",
"Newcastle", "Nowra", "Orange", "Parkes", "Port Macquarie", "Raymond Terrace", "Richmond", "Sawtell", "Singleton", "Sydney",
"Tamworth", "Taree", "Wagga Wagga", "Wollongong", "Alice Springs", "Darwin", "Bongaree", "Brisbane", "Buderim", "Bundaberg",
"Caboolture", "Cairns", "Caloundra", "Dalby", "Gladstone", "Gympie", "Kingston", "Kawana", "Mackay", "Maroochydore",
"Maryborough", "Mount Isa", "Nambour", "Nerang", "Redcliffe", "Rockhampton", "Toowoomba", "Townsville", "Warwick", "Adelaide",
"Gawler", "Mount Gambier", "Murray Bridge", "Port Augusta", "Port Lincoln", "Port Pirie", "Whyalla", "Burnie", "Devonport",
"Hobart", "Launceston", "Ulverstone", "Bacchus Marsh", "Bairnsdale", "Ballarat", "Bendigo", "Cranbourne", "Echuca", "Geelong",
"Horsham", "Palmerston", "Melbourne", "Melton", "Mildura", "Moe", "Morwell", "Colac", "Pakenham", "Portland", "Central Coast",
"Casino", "Sale", "Shepparton", "Sunbury", "Traralgon", "Wangaratta", "Warrnambool", "Albany", "Broome", "Bunbury", "Busselton",
"Geraldton", "Hervey Bay", "Kalgoorlie", "Karratha", "Kwinana Town Centre", "Mandurah", "Gold Coast", "Perth", "Port Hedland",
"Rockingham", "Bad Tatzmannsdorf", "Eisenstadt", "Grosspetersdorf", "Jennersdorf", "Landsee", "Lockenhaus", "Mattersburg",
"Neusiedl am See", "Oberpullendorf", "Oberwart", "Parndorf", "Wimpassing an der Leitha"];
