version: '2'
services:
  app:
    build: .
    command: make --no-print-directory run
    volumes:
      - ./src/gomind_runner:/workspace/src/gomind_runner
    ports:
      - "18660:18660"
    logging:
      driver: 'json-file'
